#!/bin/sh
set -e

make clean
for a in bp dp phd ; do
	rm -rf vzor-$a{,-win}
	git archive --prefix=vzor-$a/ HEAD | tar xf -
	rm -rf vzor-$a/mkdist vzor-$a/uprava
done

# BP
(
	echo "Generating BP"
	cd vzor-bp
	cp ../uprava/bp_uprava.pdf .
)

# DP
(
	echo "Generating DP"
	cd vzor-dp
	cp ../uprava/dp_uprava.pdf .
	sed -i '
		s/bp_uprava/dp_uprava/g
		s/bakaláøsk/diplomov/g
		s/BAKALÁØSK/DIPLOMOV/g
		s/bp_uprava/dp_uprava/g
	' *.tex README
	if grep -ri 'bakal' . ; then
		echo >&2 "Substitutions failed"
		exit 1
	fi
)

# PhD
(
	echo "Generating PhD"
	cd vzor-phd
	cp ../uprava/phd_uprava.pdf .
	sed -i '
		s/bakaláøské/disertaèní/g
		s/bakaláøských/disertaèních/g
		s/bakaláøskou/disertaèní/g
		s/BAKALÁØSKÁ/DISERTAÈNÍ/g
		s/bp_uprava/phd_uprava/g
		/ Následuje vevázaný /,+2d
	' *.tex README
	if grep -ri 'bakal' . ; then
		echo >&2 "Substitutions failed"
		exit 1
	fi
)

for a in bp dp phd ; do
	zip -r vzor-$a-iso.zip vzor-$a
	cp -a vzor-$a vzor-$a-win
	for c in vzor-$a-win/{*.tex,README} ; do
		recode iso-8859-2..windows-1250 $c
	done
	sed -i 's/\[latin2]/[cp1250]/g' vzor-$a-win/prace.tex
	zip -r vzor-$a-win.zip vzor-$a-win
done
