@startuml

left to right direction

class Compiler {
    __init__(lookup_file_resolver: LookupFileResolver = None)
    compile(expression: string) -> Expression
}

class Expression {
    evaluate(record: Dict[str, Any]) -> Any
}


interface LookupFileResolver {

}

@enduml
