@startuml

top to bottom direction

class Compiler {
    compile(expression: string) -> Expression
}

class Expression {
    evaluate(record: Dict[str, Any]) -> Any
}

Compiler -- Expression : creates

@enduml
