name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build thesis PDFs
    runs-on: ubuntu-latest
    container: { image: 'aergus/latex' }

    steps:
      - uses: actions/checkout@v3
      - name: Build the thesis
        run: latexmk thesis.tex -shell-escape && latexmk abstract-cs.tex -shell-escape && latexmk abstract-en.tex -shell-escape
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Thesis
          path: |
            *.pdf